### ISSUE TITLE
Issue with the modified scikit_image package

### ISSUE THREAD

**Issue by RuntimeErrorz** [ShuweiShao/NDDepth#12]
```
Traceback (most recent call last):
  File "../Estimation/nddepth/train.py", line 17, in <module>
    from utils import post_process_depth, flip_lr, silog_loss, DN_to_distance, DN_to_depth, colormap, colormap_magma, colormap_viridis, compute_errors, eval_metrics, \
  File "/home/zengdeyu/code/NDDepth/Estimation/nddepth/utils.py", line 12, in <module>
    from skimage.segmentation import all_felzenszwalb as felz_seg
  File "/home/zengdeyu/code/NDDepth/scikit-image-0.17.2/skimage/__init__.py", line 125, in <module>
    from .util.dtype import (img_as_float32,
  File "/home/zengdeyu/code/NDDepth/scikit-image-0.17.2/skimage/util/__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "/home/zengdeyu/code/NDDepth/scikit-image-0.17.2/skimage/util/_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: /home/zengdeyu/code/NDDepth/scikit-image-0.17.2/skimage/util/_remap.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
```
I have tried recompling but it still gets error above.

**Comment by RuntimeErrorz** [comment]
It seems that you have to install the exact same cudatoolkit version(11.1), and the complete command should be `conda install pytorch=1.10.0 torchvision cudatoolkit=11.1 -c nvidia -c pytorch` in case you can't install them from default channels.
